const RUBRIC = { correctness: 30, completeness: 25, robustness: 20, specificity: 15, clarity: 10 };
const REASONING = ['first-principles','inversion','analogy','adversarial','constraint-first','worked-example','socratic','contrarian','systems-thinking','decomposition','working-backwards','probabilistic','dialectical','evidence-first','expert-panel'];
const WORKFLOWS = ['draft-critique-rewrite','outline-first','test-first','research-then-synthesise','three-drafts','requirements-checklist','iterative-deepening','build-then-break','smallest-version-first','options-matrix','open-questions-first','write-then-restructure'];
const STRATEGIES = ['simplest','maximal-rigour','user-empathy','edge-cases-first','speed','defensive','clarity','completeness','fewest-moving-parts','explicit-trade-offs','built-to-last','concrete-specifics'];
function hashSeed(value) { const s=String(value); let h=2166136261>>>0; for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);} return h>>>0; }
function rngFrom(seed) { let a=hashSeed(seed)||1; return ()=>{ a|=0; a=(a+0x6D2B79F5)|0; let t=Math.imul(a^(a>>>15),1|a); t=(t+Math.imul(t^(t>>>7),61|t))^t; return ((t^(t>>>14))>>>0)/4294967296; }; }
function clampN(n){return Math.max(1,Math.min(Number.isFinite(Number(n))?Math.trunc(Number(n)):1,2160));}
export function planArena({agents}){ const n=clampN(agents); const sizes=[n]; while(sizes.at(-1)>1)sizes.push(Math.ceil(sizes.at(-1)/2)); const matches=sizes.slice(0,-1).reduce((a,x)=>a+Math.floor(x/2),0); return {strategies:n,rounds:sizes.length-1,alive_per_round:sizes,upstream_equivalent_calls:n+5*matches,mode:n>16?'full':n>4?'review':'micro'}; }
export function dealArenaCards({agents,seed}){ const n=clampN(agents); const all=[]; for(const r of REASONING)for(const w of WORKFLOWS)for(const s of STRATEGIES)all.push([r,w,s]); const rnd=rngFrom(seed); for(let i=all.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[all[i],all[j]]=[all[j],all[i]];} return {seed:String(seed),cards:all.slice(0,n).map((c,i)=>({id:`a${String(i+1).padStart(3,'0')}`,reasoning:c[0],workflow:c[1],strategy:c[2]}))}; }
export function getArenaRubric(){ return { rubric:{...RUBRIC}, formula:'(correctness*30 + completeness*25 + robustness*20 + specificity*15 + clarity*10) / 10' }; }
export function getArenaReviewChecklist({highImpact=false,github=false}={}){ const checks=['evidence-first','constraint-first','edge-cases-first','built-to-last']; if(github)checks.push('read AGENTS.md and repository instructions','verify repository, branch and target path from current state','verify result after mutation','preserve provenance and licensing'); return {mode:highImpact?'review':'micro',checks,rubric:{...RUBRIC}}; }
